name: Build CDN IP list

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Merge CDN IP
      run: |
        mkdir -p out

        cat data/*.txt > out/cdnip.txt
        sort -u out/cdnip.txt -o out/cdnip.txt

    - name: Upload CDN list
      uses: actions/upload-artifact@v4
      with:
        name: cdnip
        path: out/cdnip.txt
